apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "gcr.io/sjcc-infrastructure/{{ .Values.app.name }}:{{ .Values.app.enviroment }}-{{ .Values.app.version }}"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.app.rCpu }}
              memory: {{ .Values.app.rMemory }}
            limits:
              cpu: {{ .Values.app.lCpu }}
              memory: {{ .Values.app.lMemory }}