name: Push to GCR GitHub Action
on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Industrial/push-docker-gcr
        with:
            docker_image_name: oliverio-teste
            docker_image_tag: latest
            docker_context: ./
            gcr_host: gcr.io
            gcr_project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
            gcr_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
