name: Push to GCR GitHub Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Build
        uses: benjlevesque/actions-docker-gcr/build@v1.1
        with:
          image: oliverio-learn/cep
          registry: gcr.io
    steps:
    needs: build
      - name: Docker Push
        uses: benjlevesque/actions-docker-gcr/push@v1.1
        with:
          image: oliverio-learn/cep
          registry: gcr.io
          gcloud_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
